name: MeMyself  # 프로젝트 이름 추가
description: A new Flutter project  # 설명 추가

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6
  table_calendar: ^3.0.9
  intl: ^0.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.0.2
  dio: ^5.3.3  # 백엔드 API 통신용 추가
  cupertino_icons: ^1.0.8
  firebase_core: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

environment:
  sdk: ^3.6.2

flutter:
  uses-material-design: true
  assets:
    - .env