services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
      - ./data:/backend/data:rw
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - UPSTAGE_API_KEY=${UPSTAGE_API_KEY}
      - SYNC_INTERVAL=${SYNC_INTERVAL}
      - FAISS_BASE_PATH=${FAISS_BASE_PATH}
    restart: unless-stopped  # 서버 다운 시 자동 재시작

  scheduler:
    build: 
      context: .
      dockerfile: docker/Dockerfile.scheduler
    volumes:
      - .:/backend
      - ./data:/backend/data:rw
    environment:
      - SYNC_INTERVAL=${SYNC_INTERVAL}
      - UPSTAGE_API_KEY=${UPSTAGE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # scheduler에도 필요할 수 있음
    restart: always  # 실패시 자동 재시작

 