FROM python:3.10-slim
WORKDIR /backend
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m spacy download en_core_web_sm
COPY . .
ENV PYTHONPATH=/backend
CMD ["python", "app/scheduler.py"] 