// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCciyI2PdvHdUVQkI_AjVDXMcpZxmcLPKY',
    appId: '1:516077214206:web:3ba9e69a88b6ced44c88af',
    messagingSenderId: '516077214206',
    projectId: 'memyself-451510',
    authDomain: 'memyself-451510.firebaseapp.com',
    storageBucket: 'memyself-451510.firebasestorage.app',
    measurementId: 'G-PBHP6JY8RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUEwmZoG_-cJ-X-IZAF--VPHUUvD_ZqHk',
    appId: '1:516077214206:android:d4a949c7f05fa8eb4c88af',
    messagingSenderId: '516077214206',
    projectId: 'memyself-451510',
    storageBucket: 'memyself-451510.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_FACoJ32ekVTLUGswtoJ32Jq7fc2GtWg',
    appId: '1:516077214206:ios:1810779c1cb073b24c88af',
    messagingSenderId: '516077214206',
    projectId: 'memyself-451510',
    storageBucket: 'memyself-451510.firebasestorage.app',
    iosClientId: '516077214206-jsfc9ti3kcgt6udtaan7sdamh8fr7b19.apps.googleusercontent.com',
    iosBundleId: 'com.example.MeMyself',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCciyI2PdvHdUVQkI_AjVDXMcpZxmcLPKY',
    appId: '1:516077214206:web:d477985f459c284e4c88af',
    messagingSenderId: '516077214206',
    projectId: 'memyself-451510',
    authDomain: 'memyself-451510.firebaseapp.com',
    storageBucket: 'memyself-451510.firebasestorage.app',
    measurementId: 'G-3J5M07FHDG',
  );
}
